spring:
  datasource:
    url: jdbc:h2:mem:testdb
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: false
server:
  port: 8099
